### ISSUE TITLE
make a custom bruteforce point.

### ISSUE THREAD

**Issue by blackcodersec** [tauh33dkhan/aioresolver#2]
This tool is really good. Is it possible to custom point brute force like `-d abc.FUZZ.domain.com -w words.txt`

**Comment by tauh33dkhan** [comment]
Hi @blackcodersec,

This feature is already implemented in tool let me know if you are facing any problem.

![image](https://github.com/user-attachments/assets/36a42eca-d475-431b-a022-c18c712d7fa1)

**Comment by blackcodersec** [comment]
done :)
